#############################################################################
# Makefile for building: lgbt
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  lgbt.pro
# Template: app
# Command: C:\Qt\5.5\static\bin\qmake.exe -spec win32-g++ "CONFIG+=release" -o Makefile lgbt.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt\5.5\static\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: lgbt.pro ../Qt/5.5/static/mkspecs/win32-g++/qmake.conf ../Qt/5.5/static/mkspecs/features/spec_pre.prf \
		../Qt/5.5/static/mkspecs/qdevice.pri \
		../Qt/5.5/static/mkspecs/features/device_config.prf \
		../Qt/5.5/static/mkspecs/qconfig.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dcollision.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3drenderer.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_axbase.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_axbase_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_axcontainer.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_axserver.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_axserver_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_winextras.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_winextras_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.5/static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_assimpsceneparser.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_dsengine.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_gltfsceneparser.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qdds.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qicns.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qico.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qjp2.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qminimal.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qmng.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qsvg.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtga.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtiff.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qwebp.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_qwindows.pri \
		../Qt/5.5/static/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../Qt/5.5/static/mkspecs/features/qt_functions.prf \
		../Qt/5.5/static/mkspecs/features/qt_config.prf \
		../Qt/5.5/static/mkspecs/features/win32/qt_config.prf \
		../Qt/5.5/static/mkspecs/win32-g++/qmake.conf \
		../Qt/5.5/static/mkspecs/features/spec_post.prf \
		../Qt/5.5/static/mkspecs/features/exclusive_builds.prf \
		../Qt/5.5/static/mkspecs/features/default_pre.prf \
		../Qt/5.5/static/mkspecs/features/win32/default_pre.prf \
		../Qt/5.5/static/mkspecs/features/resolve_config.prf \
		../Qt/5.5/static/mkspecs/features/exclusive_builds_post.prf \
		../Qt/5.5/static/mkspecs/features/default_post.prf \
		../Qt/5.5/static/mkspecs/features/win32/rtti.prf \
		../Qt/5.5/static/mkspecs/features/precompile_header.prf \
		../Qt/5.5/static/mkspecs/features/warn_on.prf \
		../Qt/5.5/static/mkspecs/features/qt.prf \
		../Qt/5.5/static/mkspecs/features/resources.prf \
		../Qt/5.5/static/mkspecs/features/moc.prf \
		../Qt/5.5/static/mkspecs/features/win32/opengl.prf \
		../Qt/5.5/static/mkspecs/features/uic.prf \
		../Qt/5.5/static/mkspecs/features/win32/windows.prf \
		../Qt/5.5/static/mkspecs/features/testcase_targets.prf \
		../Qt/5.5/static/mkspecs/features/exceptions.prf \
		../Qt/5.5/static/mkspecs/features/yacc.prf \
		../Qt/5.5/static/mkspecs/features/lex.prf \
		lgbt.pro \
		C:/Qt/5.5/static/lib/qtmain.prl \
		C:/Qt/5.5/static/lib/Qt5PrintSupport.prl \
		C:/Qt/5.5/static/lib/Qt5Widgets.prl \
		C:/Qt/5.5/static/lib/Qt5Gui.prl \
		C:/Qt/5.5/static/lib/Qt5Core.prl \
		C:/Qt/5.5/static/plugins/printsupport/windowsprintersupport.prl \
		C:/Qt/5.5/static/plugins/platforms/qwindows.prl \
		C:/Qt/5.5/static/plugins/imageformats/qdds.prl \
		C:/Qt/5.5/static/plugins/imageformats/qicns.prl \
		C:/Qt/5.5/static/plugins/imageformats/qico.prl \
		C:/Qt/5.5/static/plugins/imageformats/qjp2.prl \
		C:/Qt/5.5/static/plugins/imageformats/qmng.prl \
		C:/Qt/5.5/static/plugins/imageformats/qtga.prl \
		C:/Qt/5.5/static/plugins/imageformats/qtiff.prl \
		C:/Qt/5.5/static/plugins/imageformats/qwbmp.prl \
		C:/Qt/5.5/static/plugins/imageformats/qwebp.prl
	$(QMAKE) -spec win32-g++ "CONFIG+=release" -o Makefile lgbt.pro
../Qt/5.5/static/mkspecs/features/spec_pre.prf:
../Qt/5.5/static/mkspecs/qdevice.pri:
../Qt/5.5/static/mkspecs/features/device_config.prf:
../Qt/5.5/static/mkspecs/qconfig.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dcollision.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dcollision_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3drenderer.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_3drenderer_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_axbase.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_axbase_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_axcontainer.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_axcontainer_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_axserver.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_axserver_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_core.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_help.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_location.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_network.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_script.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_winextras.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_winextras_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.5/static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_assimpsceneparser.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_dsengine.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_gltfsceneparser.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qdds.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qicns.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qico.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qjp2.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qminimal.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qmng.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qoffscreen.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qsvg.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qsvgicon.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtga.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtiff.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qwbmp.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qwebp.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_qwindows.pri:
../Qt/5.5/static/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../Qt/5.5/static/mkspecs/features/qt_functions.prf:
../Qt/5.5/static/mkspecs/features/qt_config.prf:
../Qt/5.5/static/mkspecs/features/win32/qt_config.prf:
../Qt/5.5/static/mkspecs/win32-g++/qmake.conf:
../Qt/5.5/static/mkspecs/features/spec_post.prf:
../Qt/5.5/static/mkspecs/features/exclusive_builds.prf:
../Qt/5.5/static/mkspecs/features/default_pre.prf:
../Qt/5.5/static/mkspecs/features/win32/default_pre.prf:
../Qt/5.5/static/mkspecs/features/resolve_config.prf:
../Qt/5.5/static/mkspecs/features/exclusive_builds_post.prf:
../Qt/5.5/static/mkspecs/features/default_post.prf:
../Qt/5.5/static/mkspecs/features/win32/rtti.prf:
../Qt/5.5/static/mkspecs/features/precompile_header.prf:
../Qt/5.5/static/mkspecs/features/warn_on.prf:
../Qt/5.5/static/mkspecs/features/qt.prf:
../Qt/5.5/static/mkspecs/features/resources.prf:
../Qt/5.5/static/mkspecs/features/moc.prf:
../Qt/5.5/static/mkspecs/features/win32/opengl.prf:
../Qt/5.5/static/mkspecs/features/uic.prf:
../Qt/5.5/static/mkspecs/features/win32/windows.prf:
../Qt/5.5/static/mkspecs/features/testcase_targets.prf:
../Qt/5.5/static/mkspecs/features/exceptions.prf:
../Qt/5.5/static/mkspecs/features/yacc.prf:
../Qt/5.5/static/mkspecs/features/lex.prf:
lgbt.pro:
C:/Qt/5.5/static/lib/qtmain.prl:
C:/Qt/5.5/static/lib/Qt5PrintSupport.prl:
C:/Qt/5.5/static/lib/Qt5Widgets.prl:
C:/Qt/5.5/static/lib/Qt5Gui.prl:
C:/Qt/5.5/static/lib/Qt5Core.prl:
C:/Qt/5.5/static/plugins/printsupport/windowsprintersupport.prl:
C:/Qt/5.5/static/plugins/platforms/qwindows.prl:
C:/Qt/5.5/static/plugins/imageformats/qdds.prl:
C:/Qt/5.5/static/plugins/imageformats/qicns.prl:
C:/Qt/5.5/static/plugins/imageformats/qico.prl:
C:/Qt/5.5/static/plugins/imageformats/qjp2.prl:
C:/Qt/5.5/static/plugins/imageformats/qmng.prl:
C:/Qt/5.5/static/plugins/imageformats/qtga.prl:
C:/Qt/5.5/static/plugins/imageformats/qtiff.prl:
C:/Qt/5.5/static/plugins/imageformats/qwbmp.prl:
C:/Qt/5.5/static/plugins/imageformats/qwebp.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ "CONFIG+=release" -o Makefile lgbt.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\lgbt\lgbt_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
